# Generated by Django 5.1.3 on 2024-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gasservicerequest_delete_servicerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasservicerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
